<?php
require_once __DIR__.'/../includes/admin.php'; require_role(['super_admin','admin','editor']);
$pdo=db();
if(is_post()){verify_csrf();$action=$_POST['action']??'';try{
 if($action==='save'){ $id=(int)($_POST['id']??0);$d=[trim($_POST['title_en']??''),trim($_POST['title_am']??''),trim($_POST['content_en']??''),trim($_POST['content_am']??''),($_POST['status']??'draft')==='published'?'published':'draft']; if($id){$st=$pdo->prepare('UPDATE announcements SET title_en=?,title_am=?,content_en=?,content_am=?,status=? WHERE id=?');$st->execute([...$d,$id]);log_admin("Updated announcement #$id");}else{$st=$pdo->prepare('INSERT INTO announcements(title_en,title_am,content_en,content_am,status) VALUES(?,?,?,?,?)');$st->execute($d);log_admin('Created announcement');}flash('admin_success','Announcement saved.');}
 if($action==='delete'){ $id=(int)$_POST['id'];$pdo->prepare('DELETE FROM announcements WHERE id=?')->execute([$id]);log_admin("Deleted announcement #$id");flash('admin_success','Announcement deleted.');}
}catch(Throwable $e){flash('admin_error','Could not save announcement: '.$e->getMessage());}redirect('admin/content.php');}
$edit=null;if(isset($_GET['edit'])){$st=$pdo->prepare('SELECT * FROM announcements WHERE id=?');$st->execute([(int)$_GET['edit']]);$edit=$st->fetch();}
$rows=$pdo->query('SELECT * FROM announcements ORDER BY created_at DESC')->fetchAll();
admin_page('Announcements','content','Publish bilingual announcements shown on the homepage and future announcement sections.');admin_flash();
?><div class="admin-panel"><h2><?= $edit?'Edit Announcement':'Create Announcement' ?></h2><form class="admin-form" method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=e((string)($edit['id']??0))?>"><div class="admin-form-grid"><label>Title (English)<input name="title_en" required value="<?=e($edit['title_en']??'')?>"></label><label>Title (Amharic)<input name="title_am" value="<?=e($edit['title_am']??'')?>"></label></div><div class="admin-form-grid"><label>Content (English)<textarea name="content_en" rows="5" required><?=e($edit['content_en']??'')?></textarea></label><label>Content (Amharic)<textarea name="content_am" rows="5"><?=e($edit['content_am']??'')?></textarea></label></div><label>Status<select name="status"><option value="draft" <?=($edit['status']??'draft')==='draft'?'selected':''?>>Draft</option><option value="published" <?=($edit['status']??'')==='published'?'selected':''?>>Published</option></select></label><div class="admin-actions"><button class="btn primary">Save Announcement</button><?php if($edit): ?><a class="btn outline" href="content.php">Cancel</a><?php endif; ?></div></form></div>
<div class="admin-panel"><h2>All Announcements</h2><div class="admin-table-wrap"><table class="admin-table"><tr><th>Title</th><th>Status</th><th>Created</th><th>Actions</th></tr><?php foreach($rows as $r): ?><tr><td><?=e($r['title_en'])?></td><td><span class="status <?=e($r['status'])?>"><?=e($r['status'])?></span></td><td><?=e($r['created_at'])?></td><td><a class="btn small outline" href="content.php?edit=<?=$r['id']?>">Edit</a> <form style="display:inline" method="post" onsubmit="return confirm('Delete this announcement?')"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=$r['id']?>"><button class="btn small" style="background:var(--red);color:#fff">Delete</button></form></td></tr><?php endforeach; ?></table></div></div><?php admin_end(); ?>
