<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/admin.php';
require_role(['super_admin','admin','editor']);
$pdo=db();
$q=trim($_GET['q']??''); $filter=trim($_GET['ministry']??''); $status=$_GET['status']??'active';
if(!in_array($status,['active','archived','all'],true)) $status='active';
$where=[];$params=[];
if($status!=='all'){ $where[]='status=?'; $params[]=$status; }
if($q!==''){ $where[]='(full_name LIKE ? OR department LIKE ? OR phone LIKE ?)'; array_push($params,"%$q%","%$q%","%$q%"); }
$sql='SELECT * FROM service_registrations'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY full_name ASC';
$st=$pdo->prepare($sql);$st->execute($params);$databaseRows=$st->fetchAll();$rows=[];
foreach($databaseRows as $row){$sv=json_decode((string)($row['services']??''),true);$mv=json_decode((string)($row['mobilizations']??''),true);$sv=is_array($sv)?$sv:[];$mv=is_array($mv)?$mv:[];$items=array_merge($sv,$mv);if($filter!==''&&!in_array($filter,$items,true))continue;$row['_items']=$items;$rows[]=$row;}
$logo=current_logo();
?><!doctype html><html lang="am"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Service Registrations</title><style>
@page{size:A4 landscape;margin:10mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,"Noto Sans Ethiopic","Noto Sans",sans-serif;color:#172431;font-size:9px}.header{display:flex;justify-content:space-between;align-items:center;border-bottom:2px solid #d3a341;padding-bottom:8px;margin-bottom:9px}.title h1{margin:0 0 3px;font-size:17px}.title p{margin:2px 0;color:#596773}.logo{width:48px;height:48px;object-fit:contain}.print-button{padding:7px 12px;border:0;border-radius:5px;background:#061a2b;color:#fff;margin-bottom:8px;cursor:pointer}table{width:100%;border-collapse:collapse}th{background:#061a2b;color:#fff;border:1px solid #061a2b;padding:5px;text-align:left}td{border:1px solid #d4dbe0;padding:5px;vertical-align:top}tr:nth-child(even){background:#f7f8f9}.tag{display:inline-block;border:1px solid #d3a341;border-radius:10px;padding:1px 4px;margin:1px;font-size:7px}.footer{display:flex;justify-content:space-between;margin-top:8px;color:#69757e;font-size:7px}@media print{.no-print{display:none!important}}
</style></head><body><div class="header"><div class="title"><h1>የዱራሜ ካምፖስ ወንጌላውያን ተማሪዎች ህብረት</h1><p>የአገልግሎት ዘርፍ ምዝገባ — <?=e($filter!==''?$filter:'ሁሉም ዘርፎች')?></p><p><strong><?=count($rows)?></strong> registration(s) · <?=e(ucfirst($status))?></p></div><?php if($logo):?><img class="logo" src="<?=e($logo)?>" alt="Logo"><?php endif;?></div><button class="print-button no-print" onclick="window.print()">🖨 Print / Save as PDF</button><table><thead><tr><th>#</th><th>Full Name / ሙሉ ስም</th><th>Department</th><th>Phone</th><th>Year</th><th>Services / Mobilizations</th><th>Registered</th></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="7" style="text-align:center;padding:18px">ምንም ምዝገባ አልተገኘም።</td></tr><?php else:foreach($rows as $i=>$r):?><tr><td><?=$i+1?></td><td><strong><?=e($r['full_name'])?></strong></td><td><?=e($r['department'])?></td><td><?=e($r['phone'])?></td><td><?=e($r['year_level'])?></td><td><?php foreach($r['_items'] as $x):?><span class="tag"><?=e((string)$x)?></span><?php endforeach;if(!$r['_items'])echo '-';?></td><td><?=e(date('Y-m-d',strtotime((string)$r['created_at'])))?></td></tr><?php endforeach;endif;?></tbody></table><div class="footer"><span>Durame Campus Fellowship</span><span><?=count($rows)?> Registration(s)</span><span><?=e(date('Y-m-d H:i'))?></span></div><script>window.addEventListener('load',()=>setTimeout(()=>window.print(),400));</script></body></html>
